package com.aish.mvc.tools.seed;

import java.util.List;

// Ngân hàng nội dung Đại học — 3 khối ngành (IT, IB, MKT), 22 chuyên ngành, 27 chủ đề.
// Đây là phần THIỂU SỐ so với THPT (xem ThptContentBank) — đúng tỉ lệ đa số/thiểu số
// được yêu cầu. Thêm bài mới: thêm 1 dòng t(...) vào danh sách chuyên ngành tương ứng.
final class UniversityContentBank {

    private UniversityContentBank() {
    }

    private static Topic t(String track, String domain, String title, String p1, String p2, String p3) {
        return new Topic("UNIVERSITY", track, domain, title, List.of(p1, p2, p3));
    }

    static List<Topic> all() {
        List<Topic> topics = new java.util.ArrayList<>();
        topics.addAll(it());
        topics.addAll(ib());
        topics.addAll(mkt());
        return topics;
    }

    private static List<Topic> it() {
        return List.of(
                t("IT", "SE", "Mô hình phát triển phần mềm Agile/Scrum",
                        "Agile là một tập hợp các giá trị và nguyên tắc phát triển phần mềm được công bố trong Tuyên ngôn Agile năm 2001, đề cao việc tương tác giữa các cá nhân hơn quy trình và công cụ, phần mềm chạy được hơn tài liệu đầy đủ, hợp tác với khách hàng hơn đàm phán hợp đồng, và phản hồi trước thay đổi hơn bám theo kế hoạch cứng nhắc.",
                        "Scrum là một framework cụ thể hóa Agile phổ biến nhất hiện nay, tổ chức công việc thành các Sprint có thời hạn cố định (thường 1-4 tuần), với các vai trò chính gồm Product Owner (quản lý Product Backlog), Scrum Master (hỗ trợ nhóm tuân thủ quy trình) và Development Team (thực hiện công việc).",
                        "Các sự kiện cốt lõi của Scrum gồm Sprint Planning (lập kế hoạch cho Sprint), Daily Scrum (họp đứng hàng ngày 15 phút), Sprint Review (demo sản phẩm cho stakeholder) và Sprint Retrospective (nhìn lại và cải tiến quy trình làm việc của nhóm), tạo thành một chu trình lặp liên tục giúp đội ngũ thích nghi nhanh với thay đổi yêu cầu."),
                t("IT", "SE", "Kiểm thử phần mềm và các mức kiểm thử",
                        "Kiểm thử phần mềm (software testing) là quá trình đánh giá một hệ thống hoặc thành phần phần mềm nhằm phát hiện sự khác biệt giữa kết quả thực tế và kết quả mong đợi, đồng thời đánh giá các thuộc tính của hệ thống như tính đúng đắn, hiệu năng và bảo mật.",
                        "Kiểm thử được tổ chức theo nhiều mức: unit testing kiểm tra từng đơn vị mã nguồn nhỏ nhất (hàm, phương thức) một cách độc lập; integration testing kiểm tra sự tương tác giữa các module đã tích hợp với nhau; system testing kiểm tra toàn bộ hệ thống theo yêu cầu nghiệp vụ; và acceptance testing xác nhận hệ thống đáp ứng đúng nhu cầu người dùng cuối.",
                        "Kiểm thử hộp đen (black-box) tập trung vào đầu vào/đầu ra mà không quan tâm cấu trúc mã nguồn bên trong, trong khi kiểm thử hộp trắng (white-box) dựa trên hiểu biết về cấu trúc mã nguồn để thiết kế test case, ví dụ kiểm tra độ phủ nhánh (branch coverage). Kết hợp cả hai giúp phát hiện lỗi toàn diện hơn."),
                t("IT", "AI/ML", "Học máy có giám sát: hồi quy và phân loại",
                        "Học máy có giám sát (supervised learning) là nhánh học máy trong đó mô hình được huấn luyện trên tập dữ liệu đã có nhãn (label), học ánh xạ từ đầu vào (features) sang đầu ra (target) để dự đoán nhãn cho dữ liệu mới chưa từng thấy.",
                        "Bài toán hồi quy (regression) dự đoán một giá trị liên tục, ví dụ dự đoán giá nhà dựa trên diện tích và vị trí, thường dùng các mô hình như hồi quy tuyến tính (linear regression) tối ưu hàm mất mát bình phương sai số trung bình (MSE) bằng thuật toán gradient descent.",
                        "Bài toán phân loại (classification) dự đoán một nhãn rời rạc thuộc một tập hữu hạn các lớp, ví dụ phân loại email spam/không spam, thường dùng các mô hình như hồi quy logistic, cây quyết định, hoặc Support Vector Machine, đánh giá hiệu quả qua các chỉ số như accuracy, precision, recall và F1-score."),
                t("IT", "AI/ML", "Mạng nơ-ron nhân tạo và Deep Learning cơ bản",
                        "Mạng nơ-ron nhân tạo (Artificial Neural Network) mô phỏng cách hoạt động của nơ-ron sinh học, gồm các lớp (layer) nơ-ron liên kết với nhau: lớp đầu vào (input layer), một hoặc nhiều lớp ẩn (hidden layer) và lớp đầu ra (output layer), mỗi kết nối có một trọng số (weight) được học từ dữ liệu.",
                        "Quá trình huấn luyện mạng nơ-ron sử dụng thuật toán lan truyền ngược (backpropagation) kết hợp gradient descent: tính sai số giữa dự đoán và nhãn thực tế, sau đó lan truyền ngược sai số này qua các lớp để cập nhật trọng số theo hướng giảm thiểu hàm mất mát.",
                        "Deep Learning là học máy sử dụng mạng nơ-ron có nhiều lớp ẩn (mạng sâu), cho phép tự động học các đặc trưng (feature) phức tạp từ dữ liệu thô mà không cần thiết kế đặc trưng thủ công, đạt hiệu quả vượt trội trong các bài toán thị giác máy tính (CNN) và xử lý ngôn ngữ tự nhiên (Transformer)."),
                t("IT", "DS/Big Data", "Kiến trúc xử lý dữ liệu lớn: Hadoop và Spark",
                        "Dữ liệu lớn (Big Data) được đặc trưng bởi mô hình 5V: Volume (khối lượng lớn), Velocity (tốc độ sinh ra nhanh), Variety (đa dạng định dạng: có cấu trúc, phi cấu trúc), Veracity (độ tin cậy) và Value (giá trị khai thác được), đòi hỏi các nền tảng xử lý phân tán chuyên biệt thay vì hệ thống truyền thống.",
                        "Hadoop là nền tảng mã nguồn mở cho phép lưu trữ và xử lý dữ liệu lớn phân tán trên các cụm máy tính, gồm hai thành phần cốt lõi: HDFS (Hadoop Distributed File System) để lưu trữ dữ liệu phân tán với khả năng chịu lỗi cao, và MapReduce là mô hình lập trình xử lý song song dữ liệu theo hai giai đoạn Map và Reduce.",
                        "Apache Spark ra đời sau Hadoop, khắc phục hạn chế về tốc độ của MapReduce nhờ khả năng xử lý dữ liệu trong bộ nhớ (in-memory computing), nhanh hơn Hadoop MapReduce nhiều lần với các tác vụ lặp lại, đồng thời cung cấp các thư viện tích hợp cho xử lý luồng (Spark Streaming), học máy (MLlib) và truy vấn dữ liệu có cấu trúc (Spark SQL)."),
                t("IT", "ATTT", "Mật mã học và bảo mật thông tin cơ bản",
                        "Mật mã học (cryptography) là ngành khoa học nghiên cứu các kỹ thuật bảo đảm an toàn thông tin, gồm hai nhóm thuật toán chính: mã hóa đối xứng (symmetric encryption) dùng chung một khóa cho cả mã hóa và giải mã (ví dụ AES), và mã hóa bất đối xứng (asymmetric encryption) dùng cặp khóa công khai - riêng tư (ví dụ RSA).",
                        "Hàm băm mật mã (cryptographic hash function) như SHA-256 chuyển đổi dữ liệu đầu vào có độ dài bất kỳ thành một chuỗi đầu ra có độ dài cố định, có tính chất một chiều (không thể suy ngược lại đầu vào) và nhạy với thay đổi nhỏ, được dùng để kiểm tra tính toàn vẹn dữ liệu và lưu trữ mật khẩu an toàn.",
                        "Ba nguyên tắc cốt lõi của an toàn thông tin, gọi là tam giác CIA, gồm Confidentiality (tính bảo mật - chỉ người được ủy quyền mới truy cập được thông tin), Integrity (tính toàn vẹn - thông tin không bị sửa đổi trái phép) và Availability (tính sẵn sàng - hệ thống luôn sẵn sàng phục vụ khi cần), là kim chỉ nam cho mọi giải pháp bảo mật."),
                t("IT", "Cloud", "Điện toán đám mây: mô hình IaaS, PaaS, SaaS",
                        "Điện toán đám mây (cloud computing) là mô hình cung cấp tài nguyên tính toán (máy chủ, lưu trữ, mạng, phần mềm) qua Internet theo nhu cầu sử dụng, cho phép người dùng truy cập tài nguyên linh hoạt mà không cần đầu tư, quản lý hạ tầng vật lý.",
                        "IaaS (Infrastructure as a Service) cung cấp hạ tầng ảo hóa cơ bản như máy chủ ảo, lưu trữ, mạng, người dùng tự quản lý hệ điều hành và ứng dụng trở lên; PaaS (Platform as a Service) cung cấp thêm nền tảng phát triển (hệ điều hành, runtime, database) để nhà phát triển tập trung viết ứng dụng mà không lo hạ tầng.",
                        "SaaS (Software as a Service) cung cấp phần mềm hoàn chỉnh sẵn sàng sử dụng qua trình duyệt, ví dụ Gmail, Salesforce, người dùng chỉ cần đăng ký và sử dụng mà không quản lý bất kỳ lớp hạ tầng nào bên dưới. Ba mô hình này khác nhau chủ yếu ở mức độ trách nhiệm quản lý được chuyển giao cho nhà cung cấp dịch vụ đám mây."),
                t("IT", "IS", "Hệ thống thông tin quản lý doanh nghiệp (ERP)",
                        "Hệ thống hoạch định nguồn lực doanh nghiệp (Enterprise Resource Planning - ERP) là một hệ thống thông tin tích hợp, kết nối và quản lý các hoạt động cốt lõi của doanh nghiệp như tài chính - kế toán, quản lý nhân sự, quản lý chuỗi cung ứng, sản xuất và bán hàng trên một nền tảng dữ liệu thống nhất.",
                        "Ưu điểm lớn nhất của ERP là loại bỏ tình trạng dữ liệu phân mảnh, trùng lặp giữa các phòng ban do sử dụng hệ thống riêng lẻ (data silo), giúp thông tin được cập nhật theo thời gian thực và nhất quán trên toàn tổ chức, hỗ trợ ra quyết định quản lý chính xác và kịp thời hơn.",
                        "Việc triển khai ERP đòi hỏi doanh nghiệp phải tái cấu trúc quy trình nghiệp vụ (business process reengineering) để phù hợp với hệ thống, đồng thời đối mặt với các thách thức về chi phí đầu tư lớn, thời gian triển khai dài và sự thay đổi thói quen làm việc của nhân viên trong toàn tổ chức."),
                t("IT", "GameDev", "Vòng lặp game (Game Loop) và kiến trúc engine cơ bản",
                        "Game loop là cấu trúc lập trình cốt lõi của mọi trò chơi điện tử, chạy liên tục trong suốt thời gian chơi, thực hiện tuần tự ba bước chính ở mỗi khung hình (frame): xử lý đầu vào từ người chơi (input), cập nhật trạng thái thế giới game (update) và vẽ hình ảnh lên màn hình (render).",
                        "Một thách thức kỹ thuật quan trọng của game loop là đảm bảo tốc độ mô phỏng game (game simulation) không phụ thuộc vào tốc độ khung hình thực tế của máy chạy, thường được giải quyết bằng kỹ thuật fixed timestep (cập nhật logic game theo bước thời gian cố định) kết hợp nội suy (interpolation) khi render.",
                        "Game engine hiện đại như Unity hay Unreal Engine cung cấp sẵn kiến trúc thành phần (Entity-Component-System) cho phép nhà phát triển xây dựng đối tượng game bằng cách kết hợp các thành phần độc lập (vị trí, hình ảnh, vật lý, điều khiển), giúp tái sử dụng mã nguồn linh hoạt hơn so với kiến trúc kế thừa truyền thống."),
                t("IT", "UI/UX", "Nguyên tắc thiết kế trải nghiệm người dùng (UX)",
                        "Trải nghiệm người dùng (User Experience - UX) là toàn bộ cảm nhận, cảm xúc của người dùng khi tương tác với một sản phẩm số, không chỉ giới hạn ở giao diện (UI) mà bao gồm cả tính hữu dụng, khả năng sử dụng, khả năng tiếp cận và giá trị mà sản phẩm mang lại.",
                        "Quy trình thiết kế UX theo phương pháp thiết kế lấy người dùng làm trung tâm (user-centered design) thường gồm các bước: nghiên cứu người dùng (user research), xây dựng chân dung người dùng (persona), thiết kế wireframe và prototype, kiểm thử khả năng sử dụng (usability testing) và lặp lại cải tiến dựa trên phản hồi thực tế.",
                        "Các nguyên tắc thiết kế UX phổ biến gồm tính nhất quán (consistency - các thành phần giao diện hoạt động thống nhất), khả năng phản hồi (feedback - hệ thống luôn thông báo trạng thái cho người dùng), và nguyên tắc Fitts's Law (mục tiêu càng lớn và càng gần con trỏ thì càng dễ và nhanh để nhấn trúng)."),
                t("IT", "Embedded", "Lập trình vi điều khiển và hệ thống nhúng cơ bản",
                        "Hệ thống nhúng (embedded system) là hệ thống máy tính chuyên dụng được thiết kế để thực hiện một hoặc một số chức năng cụ thể trong một hệ thống lớn hơn, khác với máy tính đa năng, thường có ràng buộc chặt chẽ về tài nguyên bộ nhớ, năng lượng tiêu thụ và thời gian đáp ứng thực (real-time).",
                        "Vi điều khiển (microcontroller) là bộ não trung tâm của hầu hết hệ thống nhúng, tích hợp CPU, bộ nhớ (RAM, Flash) và các ngoại vi (GPIO, UART, ADC, PWM) trên cùng một chip, cho phép lập trình để đọc tín hiệu từ cảm biến và điều khiển các thiết bị chấp hành (actuator) như động cơ, đèn LED.",
                        "Lập trình hệ thống nhúng thường sử dụng ngôn ngữ C/C++ do khả năng thao tác trực tiếp với phần cứng và hiệu năng cao, đồng thời phải quan tâm đến hệ điều hành thời gian thực (RTOS) khi hệ thống cần xử lý nhiều tác vụ đồng thời với yêu cầu nghiêm ngặt về thời gian đáp ứng.")
        );
    }

    private static List<Topic> ib() {
        return List.of(
                t("IB", "XNK", "Quy trình xuất nhập khẩu hàng hóa quốc tế",
                        "Quy trình xuất khẩu hàng hóa quốc tế thường gồm các bước chính: đàm phán và ký kết hợp đồng ngoại thương, chuẩn bị hàng hóa và kiểm tra chất lượng, làm thủ tục hải quan xuất khẩu, thuê phương tiện vận tải và mua bảo hiểm hàng hóa, cuối cùng là giao hàng và hoàn tất bộ chứng từ thanh toán.",
                        "Bộ chứng từ xuất nhập khẩu đóng vai trò quan trọng trong toàn bộ quy trình, bao gồm hóa đơn thương mại (Commercial Invoice), phiếu đóng gói (Packing List), vận đơn (Bill of Lading), giấy chứng nhận xuất xứ (Certificate of Origin - C/O) và các chứng từ bảo hiểm, kiểm dịch tùy loại hàng hóa cụ thể.",
                        "Thủ tục hải quan là khâu bắt buộc trong xuất nhập khẩu, doanh nghiệp phải khai báo hải quan điện tử, nộp thuế xuất nhập khẩu (nếu có) và các loại thuế liên quan, đồng thời tuân thủ các quy định về kiểm tra chuyên ngành đối với một số mặt hàng đặc thù trước khi hàng hóa được thông quan."),
                t("IB", "XNK", "Incoterms 2020 trong thương mại quốc tế",
                        "Incoterms (International Commercial Terms) là bộ quy tắc thương mại quốc tế do Phòng Thương mại Quốc tế (ICC) ban hành, quy định rõ trách nhiệm, chi phí và rủi ro giữa người bán và người mua trong giao dịch mua bán hàng hóa quốc tế, phiên bản mới nhất là Incoterms 2020.",
                        "Incoterms 2020 gồm 11 điều kiện, chia thành hai nhóm: nhóm áp dụng cho mọi phương thức vận tải (như EXW, FCA, CIP, DAP, DDP) và nhóm chỉ áp dụng cho vận tải đường biển và đường thủy nội địa (như FOB, CIF, CFR), mỗi điều kiện xác định rõ điểm chuyển giao rủi ro và ai chịu trách nhiệm thuê phương tiện, mua bảo hiểm.",
                        "Việc lựa chọn điều kiện Incoterms phù hợp ảnh hưởng trực tiếp đến giá thành, mức độ rủi ro mà mỗi bên gánh chịu; ví dụ điều kiện FOB (Free On Board) người bán chỉ chịu trách nhiệm đến khi hàng qua lan can tàu tại cảng xếp hàng, trong khi điều kiện CIF (Cost, Insurance and Freight) người bán phải chịu thêm chi phí vận chuyển và bảo hiểm đến cảng đích."),
                t("IB", "SCM", "Quản trị chuỗi cung ứng toàn cầu",
                        "Quản trị chuỗi cung ứng (Supply Chain Management) là việc hoạch định, tổ chức và kiểm soát toàn bộ dòng chảy nguyên vật liệu, thông tin và tài chính từ nhà cung cấp nguyên liệu thô, qua các khâu sản xuất, đến tay người tiêu dùng cuối cùng, nhằm tối ưu chi phí và đáp ứng nhu cầu khách hàng hiệu quả nhất.",
                        "Chuỗi cung ứng toàn cầu ngày nay đối mặt với nhiều thách thức phức tạp hơn chuỗi cung ứng nội địa: khác biệt múi giờ, ngôn ngữ, quy định pháp lý và thuế quan giữa các quốc gia, rủi ro địa chính trị, cùng độ trễ vận chuyển dài hơn đòi hỏi mức tồn kho an toàn (safety stock) lớn hơn.",
                        "Hiệu ứng Bullwhip (hiệu ứng cái roi da) là hiện tượng biến động nhỏ về nhu cầu ở khâu bán lẻ bị khuếch đại dần qua các khâu ngược dòng chuỗi cung ứng (nhà phân phối, nhà sản xuất, nhà cung cấp nguyên liệu), gây ra tình trạng dư thừa hoặc thiếu hụt tồn kho nghiêm trọng nếu không có sự chia sẻ thông tin nhu cầu hiệu quả giữa các mắt xích."),
                t("IB", "Logistics", "Vận tải đa phương thức trong logistics quốc tế",
                        "Vận tải đa phương thức (multimodal transport) là phương thức vận chuyển hàng hóa sử dụng ít nhất hai loại hình vận tải khác nhau (đường biển, đường bộ, đường sắt, đường hàng không) dưới một hợp đồng vận tải duy nhất, do một người kinh doanh vận tải đa phương thức (MTO) chịu trách nhiệm toàn trình.",
                        "Ưu điểm nổi bật của vận tải đa phương thức là giảm thiểu thời gian và chi phí xử lý hàng hóa tại các điểm chuyển tải nhờ sử dụng container tiêu chuẩn hóa xuyên suốt hành trình, đơn giản hóa thủ tục chứng từ vì chỉ cần một bộ vận đơn duy nhất (through bill of lading) cho toàn bộ chặng vận chuyển.",
                        "Các trung tâm logistics và cảng cạn (Inland Container Depot - ICD) đóng vai trò quan trọng trong vận tải đa phương thức, là nơi trung chuyển, lưu kho và làm thủ tục hải quan cho hàng hóa trước khi tiếp tục hành trình bằng phương thức vận tải khác, giúp giảm tải cho các cảng biển lớn."),
                t("IB", "I-Marketing", "Chiến lược marketing quốc tế và thích nghi văn hóa",
                        "Marketing quốc tế là hoạt động marketing được thực hiện xuyên biên giới quốc gia, đòi hỏi doanh nghiệp phải nghiên cứu và thích nghi với sự khác biệt về văn hóa, ngôn ngữ, thói quen tiêu dùng, hệ thống pháp luật và điều kiện kinh tế của từng thị trường mục tiêu cụ thể.",
                        "Doanh nghiệp quốc tế thường lựa chọn giữa chiến lược tiêu chuẩn hóa (standardization - giữ nguyên sản phẩm và thông điệp marketing trên toàn cầu để tiết kiệm chi phí) và chiến lược thích nghi hóa (adaptation - điều chỉnh sản phẩm, bao bì, thông điệp cho phù hợp với từng thị trường địa phương) tùy vào đặc thù ngành hàng và mức độ khác biệt văn hóa.",
                        "Mô hình các chiều văn hóa của Hofstede (khoảng cách quyền lực, chủ nghĩa cá nhân/tập thể, mức độ né tránh rủi ro...) là công cụ hữu ích giúp nhà marketing quốc tế hiểu và dự đoán hành vi tiêu dùng khác biệt giữa các nền văn hóa, từ đó xây dựng chiến lược định vị và truyền thông phù hợp cho từng thị trường."),
                t("IB", "I-Finance", "Quản trị rủi ro tỷ giá trong tài chính quốc tế",
                        "Rủi ro tỷ giá (exchange rate risk) là rủi ro phát sinh khi giá trị của các khoản thu, chi hoặc tài sản, nợ phải trả bằng ngoại tệ biến động do sự thay đổi của tỷ giá hối đoái, ảnh hưởng trực tiếp đến lợi nhuận và dòng tiền của doanh nghiệp có hoạt động kinh doanh quốc tế.",
                        "Rủi ro tỷ giá được phân thành ba loại chính: rủi ro giao dịch (transaction risk) phát sinh từ các hợp đồng mua bán cụ thể bằng ngoại tệ, rủi ro chuyển đổi (translation risk) phát sinh khi hợp nhất báo cáo tài chính của công ty con ở nước ngoài, và rủi ro kinh tế (economic risk) ảnh hưởng đến giá trị doanh nghiệp trong dài hạn.",
                        "Các công cụ phòng ngừa rủi ro tỷ giá phổ biến gồm hợp đồng kỳ hạn (forward contract - khóa tỷ giá cho một giao dịch trong tương lai), hợp đồng quyền chọn (option - có quyền nhưng không bắt buộc thực hiện giao dịch theo tỷ giá đã thỏa thuận) và hợp đồng hoán đổi (swap), giúp doanh nghiệp ổn định dòng tiền trước biến động tỷ giá."),
                t("IB", "I-Finance", "Thanh toán quốc tế: L/C và các phương thức khác",
                        "Thư tín dụng (Letter of Credit - L/C) là phương thức thanh toán quốc tế phổ biến và an toàn nhất, trong đó ngân hàng phát hành cam kết trả tiền cho người xuất khẩu khi người này xuất trình được bộ chứng từ phù hợp hoàn toàn với các điều khoản và điều kiện quy định trong L/C.",
                        "Ngoài L/C, thương mại quốc tế còn sử dụng các phương thức thanh toán khác với mức độ rủi ro và chi phí khác nhau: chuyển tiền bằng điện (Telegraphic Transfer - T/T) đơn giản, nhanh nhưng rủi ro cao hơn nếu trả trước; nhờ thu kèm chứng từ (Documentary Collection) có mức an toàn trung bình, chi phí thấp hơn L/C.",
                        "Việc lựa chọn phương thức thanh toán phù hợp phụ thuộc vào mức độ tin cậy giữa hai bên mua bán, giá trị hợp đồng, và vị thế đàm phán của mỗi bên: đối tác mới, giao dịch giá trị lớn thường ưu tiên L/C để giảm thiểu rủi ro, trong khi đối tác lâu năm, tin cậy cao có thể sử dụng T/T trả sau để tiết kiệm chi phí và thời gian."),
                t("IB", "Trade Compliance", "Tuân thủ thương mại và các rào cản phi thuế quan",
                        "Tuân thủ thương mại (trade compliance) là việc doanh nghiệp đảm bảo mọi hoạt động xuất nhập khẩu tuân thủ đầy đủ các quy định pháp luật trong nước và quốc tế, bao gồm quy định về thuế quan, kiểm soát xuất khẩu, cấm vận kinh tế và các hiệp định thương mại mà quốc gia tham gia.",
                        "Rào cản phi thuế quan (non-tariff barriers) là các biện pháp hạn chế thương mại không dùng thuế, bao gồm hạn ngạch nhập khẩu (quota), quy định về tiêu chuẩn kỹ thuật, yêu cầu kiểm dịch động thực vật (SPS), quy tắc xuất xứ (rules of origin) và các thủ tục hành chính phức tạp gây khó khăn cho hàng hóa nhập khẩu.",
                        "Doanh nghiệp xuất nhập khẩu cần xây dựng bộ phận hoặc quy trình tuân thủ thương mại chuyên trách để cập nhật liên tục các thay đổi về chính sách thương mại giữa các quốc gia, tránh rủi ro pháp lý như bị phạt, tịch thu hàng hóa, hoặc mất quyền tiếp cận thị trường xuất khẩu quan trọng.")
        );
    }

    private static List<Topic> mkt() {
        return List.of(
                t("MKT", "Digital MKT", "Chiến lược Digital Marketing tích hợp (Omnichannel)",
                        "Digital Marketing tích hợp đa kênh (omnichannel marketing) là chiến lược kết hợp nhất quán nhiều kênh số (website, mạng xã hội, email, ứng dụng di động, quảng cáo trả phí) để mang lại trải nghiệm liền mạch, thống nhất cho khách hàng dù họ tương tác qua bất kỳ điểm chạm (touchpoint) nào.",
                        "Khác với marketing đa kênh (multichannel) truyền thống nơi các kênh hoạt động độc lập, omnichannel đòi hỏi dữ liệu khách hàng được đồng bộ hóa xuyên suốt các kênh, cho phép khách hàng bắt đầu hành trình mua sắm trên một kênh và tiếp tục liền mạch trên kênh khác mà không bị gián đoạn trải nghiệm.",
                        "Để triển khai omnichannel hiệu quả, doanh nghiệp cần đầu tư vào nền tảng quản lý dữ liệu khách hàng (Customer Data Platform - CDP) để có cái nhìn 360 độ về khách hàng, đồng thời phối hợp chặt chẽ giữa các đội ngũ phụ trách từng kênh để đảm bảo thông điệp thương hiệu nhất quán trên toàn bộ hệ sinh thái tiếp thị."),
                t("MKT", "Digital MKT", "Digital Marketing Funnel và hành trình khách hàng",
                        "Phễu marketing số (digital marketing funnel) mô tả hành trình khách hàng từ khi chưa biết đến thương hiệu cho tới khi trở thành khách hàng trung thành, thường gồm các giai đoạn: Awareness (nhận biết), Consideration (cân nhắc), Conversion (chuyển đổi) và Retention/Loyalty (giữ chân, trung thành).",
                        "Ở mỗi giai đoạn của phễu, doanh nghiệp cần áp dụng các chiến thuật và chỉ số đo lường khác nhau: giai đoạn Awareness tập trung vào quảng cáo hiển thị, nội dung lan tỏa để tăng độ nhận diện thương hiệu; giai đoạn Conversion tập trung tối ưu tỉ lệ chuyển đổi (Conversion Rate Optimization) trên trang đích (landing page).",
                        "Việc theo dõi hành trình khách hàng xuyên suốt phễu thông qua các công cụ phân tích (như Google Analytics) giúp doanh nghiệp xác định điểm nghẽn (drop-off point) - nơi khách hàng tiềm năng rời bỏ nhiều nhất, từ đó tối ưu từng giai đoạn để cải thiện tỉ lệ chuyển đổi tổng thể của toàn bộ phễu marketing."),
                t("MKT", "Brand", "Xây dựng và định vị thương hiệu (Brand Positioning)",
                        "Định vị thương hiệu (brand positioning) là quá trình tạo dựng một vị trí riêng biệt, rõ ràng trong tâm trí khách hàng mục tiêu so với các đối thủ cạnh tranh, trả lời câu hỏi thương hiệu đại diện cho điều gì và tại sao khách hàng nên lựa chọn thương hiệu đó thay vì các lựa chọn khác.",
                        "Một tuyên bố định vị (positioning statement) hiệu quả thường xác định rõ bốn yếu tố: đối tượng khách hàng mục tiêu, ngành hàng hoặc bối cảnh cạnh tranh, lợi ích cốt lõi khác biệt mà thương hiệu mang lại (unique value proposition), và lý do khách hàng có thể tin tưởng vào lợi ích đó (reason to believe).",
                        "Bộ nhận diện thương hiệu (brand identity) gồm các yếu tố hữu hình như logo, màu sắc, phông chữ, giọng điệu truyền thông (tone of voice) cần được thể hiện nhất quán trên mọi điểm chạm với khách hàng, góp phần củng cố nhận thức và sự ghi nhớ về định vị thương hiệu đã xây dựng theo thời gian."),
                t("MKT", "SEO/SEM", "Tối ưu hóa công cụ tìm kiếm (SEO) căn bản",
                        "SEO (Search Engine Optimization) là tập hợp các kỹ thuật nhằm cải thiện thứ hạng của một website trên trang kết quả tìm kiếm tự nhiên (organic search results) của các công cụ tìm kiếm như Google, từ đó tăng lượng truy cập miễn phí mà không phải trả tiền quảng cáo trực tiếp.",
                        "SEO được chia thành ba nhóm kỹ thuật chính: SEO On-page tối ưu các yếu tố trên chính trang web (tiêu đề, thẻ meta, cấu trúc heading, nội dung chất lượng, tốc độ tải trang); SEO Off-page xây dựng uy tín thông qua liên kết từ các trang khác trỏ về (backlink); và SEO Technical đảm bảo website dễ dàng được thu thập dữ liệu (crawl) và lập chỉ mục (index) bởi công cụ tìm kiếm.",
                        "Nghiên cứu từ khóa (keyword research) là bước nền tảng của mọi chiến lược SEO, giúp xác định những cụm từ mà khách hàng mục tiêu thực sự tìm kiếm, từ đó xây dựng nội dung đáp ứng đúng ý định tìm kiếm (search intent) của người dùng — yếu tố ngày càng được các thuật toán tìm kiếm hiện đại ưu tiên đánh giá."),
                t("MKT", "Content", "Chiến lược Content Marketing hiệu quả",
                        "Content Marketing là phương pháp tiếp thị tập trung vào việc tạo ra và phân phối nội dung có giá trị, liên quan và nhất quán nhằm thu hút, giữ chân một đối tượng khán giả được xác định rõ ràng, và cuối cùng thúc đẩy hành động sinh lợi từ khách hàng, thay vì quảng cáo trực tiếp về sản phẩm.",
                        "Một chiến lược content marketing hiệu quả bắt đầu từ việc thấu hiểu chân dung khách hàng mục tiêu (buyer persona) và những vấn đề, câu hỏi họ đang tìm kiếm câu trả lời ở từng giai đoạn của hành trình mua hàng, từ đó xây dựng lịch nội dung (content calendar) phù hợp cho từng giai đoạn đó.",
                        "Việc đo lường hiệu quả content marketing không chỉ dựa vào lượt xem hay lượt thích, mà cần tập trung vào các chỉ số gắn với mục tiêu kinh doanh như tỉ lệ chuyển đổi từ nội dung sang khách hàng tiềm năng (lead), thời gian đọc trung bình, và giá trị vòng đời khách hàng (Customer Lifetime Value) được tạo ra từ các kênh nội dung."),
                t("MKT", "CRM", "Quản trị quan hệ khách hàng (CRM) trong doanh nghiệp",
                        "Quản trị quan hệ khách hàng (Customer Relationship Management - CRM) là chiến lược và hệ thống công nghệ giúp doanh nghiệp quản lý, phân tích các tương tác với khách hàng hiện tại và tiềm năng trong suốt vòng đời quan hệ, nhằm cải thiện sự hài lòng, giữ chân khách hàng và tăng doanh thu.",
                        "Hệ thống phần mềm CRM tập trung dữ liệu khách hàng từ nhiều nguồn (bán hàng, chăm sóc khách hàng, marketing) vào một nền tảng thống nhất, giúp đội ngũ kinh doanh theo dõi lịch sử tương tác, dự báo doanh số và cá nhân hóa cách tiếp cận từng khách hàng dựa trên dữ liệu hành vi thực tế.",
                        "Phân khúc khách hàng dựa trên mô hình RFM (Recency - độ gần đây, Frequency - tần suất, Monetary - giá trị chi tiêu) là kỹ thuật CRM phổ biến giúp doanh nghiệp xác định nhóm khách hàng giá trị cao cần ưu tiên chăm sóc, cũng như nhóm khách hàng có nguy cơ rời bỏ (churn) cần có chính sách giữ chân kịp thời."),
                t("MKT", "Growth", "Growth Hacking: tăng trưởng người dùng bền vững",
                        "Growth Hacking là phương pháp tiếp cận tăng trưởng tập trung vào thử nghiệm nhanh (rapid experimentation) trên nhiều kênh marketing và phát triển sản phẩm khác nhau, nhằm tìm ra những cách hiệu quả nhất để tăng trưởng người dùng, doanh thu với nguồn lực hạn chế, thường gắn liền với các công ty khởi nghiệp công nghệ.",
                        "Khung AARRR (còn gọi là Pirate Metrics), gồm Acquisition (thu hút người dùng mới), Activation (kích hoạt trải nghiệm giá trị đầu tiên), Retention (giữ chân), Referral (giới thiệu) và Revenue (doanh thu), là mô hình phổ biến giúp đội ngũ growth xác định giai đoạn nào trong hành trình người dùng đang có vấn đề cần cải thiện nhất.",
                        "Vòng lặp thử nghiệm growth hacking điển hình gồm: đặt giả thuyết dựa trên dữ liệu, thiết kế thử nghiệm A/B với quy mô nhỏ, đo lường kết quả dựa trên chỉ số đã xác định trước, và nhanh chóng nhân rộng nếu hiệu quả hoặc loại bỏ nếu không, cho phép đội ngũ học hỏi và tối ưu liên tục với tốc độ cao hơn marketing truyền thống."),
                t("MKT", "E-commerce", "Mô hình kinh doanh thương mại điện tử B2C/B2B",
                        "Thương mại điện tử B2C (Business-to-Consumer) là mô hình doanh nghiệp bán hàng hóa, dịch vụ trực tiếp cho người tiêu dùng cá nhân qua các nền tảng trực tuyến như website riêng hoặc sàn thương mại điện tử (Shopee, Lazada), đặc trưng bởi số lượng đơn hàng lớn nhưng giá trị mỗi đơn thường nhỏ.",
                        "Thương mại điện tử B2B (Business-to-Business) là mô hình giao dịch giữa các doanh nghiệp với nhau, thường có giá trị đơn hàng lớn hơn nhiều, quy trình mua hàng phức tạp hơn với nhiều bên phê duyệt, và chu kỳ bán hàng dài hơn so với B2C, đòi hỏi nền tảng hỗ trợ báo giá tùy chỉnh, đàm phán hợp đồng.",
                        "Yếu tố thành công cốt lõi trong thương mại điện tử bao gồm trải nghiệm mua sắm liền mạch trên thiết bị di động, hệ thống thanh toán đa dạng và an toàn, tối ưu chuỗi cung ứng và giao vận (fulfillment) để rút ngắn thời gian giao hàng, cùng chiến lược giữ chân khách hàng thông qua các chương trình khách hàng thân thiết.")
        );
    }
}
