package com.aish.mvc.entity.enums;

public enum NotificationType {
    REPORT_CREATED,
    REPORT_RESOLVED,
    DOCUMENT_SCREENED,
    COMMENT_UNDER_REVIEW,
    COMMENT_REVIEWED,
    METADATA_MISMATCH,
    DOCUMENT_SHARED,
    DOC_APPROVED,
    DOC_REJECTED,
    APPEAL_APPROVED,
    APPEAL_REJECTED,
    COMMENT_ON_MY_DOC,
    RATING_ON_MY_DOC
}
