# Chỉ đường cho web chọc vào đúng Database ở cổng 8080
spring.datasource.url=jdbc:postgresql://localhost:8080/ai_study_db
spring.datasource.username=postgres
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Web sẽ chạy ở cổng 8088 để không đụng hàng với Database
server.port=8088