# Kết nối Database (Hãy chắc chắn Postgres của bạn đang nghe ở cổng 8080)
spring.datasource.url=jdbc:postgresql://localhost:8080/ai_study_db
spring.datasource.username=postgres
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA & Hibernate
# Để 'none' vì bạn đã tạo bảng bằng tay (24 bảng) rất chuẩn rồi
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server Port
server.port=8088

# Tắt thông báo warning Open-In-View trong Log
spring.jpa.open-in-view=true